//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Project2ModelingLib
{
    public class ChickenFarm
    {
        private int chickenPrice;
        private int _numberOfPriceCuts;

        public virtual int GetPrice()
        {
            throw new System.NotImplementedException();
        }

        public virtual void ChangePrice()
        {
            throw new System.NotImplementedException();
        }

        public virtual void FarmerFunc()
        {
            throw new System.NotImplementedException();
        }

    }
}
