//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;

namespace Project2ModelingLib
{
    public class OrderProcessing
    {
        public bool CheckCreditCard(int ccNumber)
        {
            throw new System.NotImplementedException();
        }

        public int CalculateCharge(int chickens, int unitPrice)
        {
            throw new System.NotImplementedException();
        }

        public void ProcessOrder()
        {
            throw new System.NotImplementedException();
        }
    }
}

