//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;

public class Order
{
    /// <summary>
    /// The identity of the sender.
    /// </summary>
    private string senderId;

    /// <summary>
    /// the credit card number.
    /// </summary>
    private int cardNo;

    /// <summary>
    /// the number of chickens to purchase.
    /// </summary>
    private int amount;

    /// <summary>
    /// The identity of the sender.
    /// </summary>
    public string SenderId
    {
        get { return senderId; }
        set { senderId = value; }
    }

    /// <summary>
    /// the credit card number.
    /// </summary>
    public int CardNo
    {
        get { return cardNo; }
        set { cardNo = value; }
    }

    /// <summary>
    /// the number of chickens to purchase.
    /// </summary>
    public int Amount
    {
        get { return amount; }
        set { amount = value; }
    }

    /// <summary>
    /// Encodes the order into a string type.
    /// </summary>
    /// <returns>The order encoded as a string.</returns>
    public virtual string Encode()
    {
        System.Xml.Serialization.XmlSerializer serializer = new System.Xml.Serialization.XmlSerializer(this.GetType());
        StringWriter writer = new StringWriter();
        serializer.Serialize(writer, this);
        return writer.ToString();
    }

    /// <summary>
    /// Creates an order object from a encoded order string.
    /// </summary>
    /// <param name="orderString">The string representing the order.</param>
    /// <returns>The order.</returns>
    public static Order Decode(string orderString)
    {
        System.Xml.Serialization.XmlSerializer serializer = new System.Xml.Serialization.XmlSerializer(typeof(Order));
        StringReader reader = new StringReader(orderString);
        return (Order) serializer.Deserialize(reader);
    }

    public DateTime CreatedTime
	{
		get;
		set;
	}



	public TimeSpan OrderTime
	{
		get;
		set;
	}



    // These are to meet requirements. C# uses properties so use the properties instead.
	public virtual void setID(string id)
	{
        senderId = id;
	}

	public virtual string getID()
	{
        return senderId;
	}

	public virtual void setCardNo(int number)
	{
        cardNo = number;
	}

	public virtual int getCardNo()
	{
        return cardNo;
	}

	public virtual int getAmount()
	{
        return amount;
	}

	public virtual void setAmount(int amt)
	{
        amount = amt;
	}

}

