//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Project2ModelingLib
{
    public class OrderProcessor
    {
        public virtual bool CheckCreditCard(int ccNumber)
        {
            throw new System.NotImplementedException();
        }

        public virtual int CalculateCharge(int chickens, int unitPrice)
        {
            throw new System.NotImplementedException();
        }

        public virtual void ProcessOrder()
        {
            throw new System.NotImplementedException();
        }
    }
}

