//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Order
{
	private string senderId
	{
		get;
		set;
	}

	private int cardNo
	{
		get;
		set;
	}

	private int amount
	{
		get;
		set;
	}

	private DateTime receiveTime
	{
		get;
		set;
	}

	private TimeSpan orderTime
	{
		get;
		set;
	}

	public virtual void SetID(string id)
	{
		throw new System.NotImplementedException();
	}

	public virtual string GetID()
	{
		throw new System.NotImplementedException();
	}

	public virtual void SetCardNo(int number)
	{
		throw new System.NotImplementedException();
	}

	public virtual int GetCardNo()
	{
		throw new System.NotImplementedException();
	}

	public virtual int GetAmount()
	{
		throw new System.NotImplementedException();
	}

	public virtual void SetAmount(int amt)
	{
		throw new System.NotImplementedException();
	}

	public virtual string Encode()
	{
		throw new System.NotImplementedException();
	}

	public static Order Decode(string orderString)
	{
		throw new System.NotImplementedException();
	}

}

