//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Project2ModelingLib
{
    public class MultiCellBuffer
    {
        public virtual void GetOneCell()
        {
            throw new System.NotImplementedException();
        }

        public virtual void SetOneCell(string encoded)
        {
            throw new System.NotImplementedException();
        }

        public event EventHandler<NewCellEventArgs> NewCellEvent;

        public void OnNewCellEvent(NewCellEventArgs e)
        {
            EventHandler<NewCellEventArgs> handler = NewCellEvent;
            if (handler != null)
            {
                handler(this, e);
            }
        }
    }
}

